import { Controller, Post, Body, UnauthorizedException } from '@nestjs/common';
import { CreateUserDto } from '@/users/dto/create-user.dto';
import { AuthService } from './auth.service';
import { CredentialsDto } from '@/users/dto/credetials.dto';

@Controller('auth')
export class AuthController {
  constructor(private authService: AuthService) {}

  @Post('/signup')
  async signUp(
    @Body() createUserDto: CreateUserDto,
  ): Promise<{ message: string }> {
    await this.authService.signUp(createUserDto);
    return {
      message: 'Cadastro realizado com sucesso',
    };
  }

  @Post('/signin')
  async signIn(
    @Body() credentialsDto: CredentialsDto,
  ): Promise<{ message: string }> {
    const user = await this.authService.signIn(credentialsDto);

    if (user === null) {
      throw new UnauthorizedException('Credenciais inv√°lidas');
    }

    return {
      message: 'Login realizado com sucesso',
    };
  }
}
